import type { Metadata } from "next";
import {
  Herr_Von_Muellerhoff,
  Monoton,
  Orbitron,
  Russo_One,
} from "next/font/google";
import "./globals.css";
import Cursor from "@/shared/ui/Cursor";

const herrvon_font = Herr_Von_Muellerhoff({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-herrvon",
  weight: "400",
});

const RussoOne_font = Russo_One({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-russo",
  weight: "400",
});

const Orbitron_font = Orbitron({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-orbitron",
  weight: "400",
});

const monoton_font = Monoton({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-monoton",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Portfolio Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${RussoOne_font.variable} ${Orbitron_font.variable} ${monoton_font.variable} ${herrvon_font.variable} overflow-x-hidden select-none`}
      >
        {children}
      </body>
    </html>
  );
}
